export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USER_INFO_RECEIVED = 'USER_INFO_RECEIVED';
export const GET_SURVEY_LIST_SUCCESS = 'GET_SURVEY_LIST_SUCCESS';
export const GET_SURVEY_LIST_ERROR = 'GET_SURVEY_LIST_ERROR';
export const CHANGE_PUBLISH_STATUS_SUCCESS = 'CHANGE_PUBLISH_STATUS_SUCCESS';
export const CHANGE_PUBLISH_STATUS_ERROR = 'CHANGE_PUBLISH_STATUS_ERROR';
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS';
export const DELETE_SURVEY_ERROR = 'DELETE_SURVEY_ERROR';
export const GET_SURVEY_RESPONSES_SUCCESS = 'GET_SURVEY_RESPONSES_SUCCESS';
export const GET_SURVEY_RESPONSES_ERROR = 'GET_SURVEY_RESPONSES_ERROR';
export const GET_SURVEY_RESPONSES_GRAPHICAL_SUCCESS = 'GET_SURVEY_RESPONSES_GRAPHICAL_SUCCESS';
export const GET_SURVEY_RESPONSES_GRAPHICAL_ERROR = 'GET_SURVEY_RESPONSES_GRAPHICAL_ERROR';
export const SUMMARY_SUCCESS = 'SUMMARY_SUCCESS';
export const SUMMARY_FAILURE = 'SUMMARY_FAILURE';
export const SAVE_TITLE = 'SAVE_TITLE';
export const SAVE_DESCRIPTION = 'SAVE_DESCRIPTION';
export const GET_BULK_ANSWER_LIST_SUCCESS = 'GET_BULK_ANSWER_LIST_SUCCESS';
export const GET_BULK_ANSWER_LIST_ERROR = 'GET_BULK_ANSWER_LIST_ERROR';
export const BULK_ANSWER_SUBMIT_SUCCESS = 'BULK_ANSWER_SUBMIT_SUCCESS';
export const BULK_ANSWER_SUBMIT_ERROR = 'BULK_ANSWER_SUBMIT_ERROR';
export const SET_ANSWER_LIST = 'SET_ANSWER_LIST';
export const SAVE_SURVEY = 'SAVE_SURVEY_SUCCESS';
export const CLEAR_SURVEY = 'CLEAR_SURVEY';
export const SAVE_SURVEY_FAILURE = 'SAVE_SURVEY_FAILURE';
export const CAN_SAVE_TEMPLATE = 'CAN_SAVE_TEMPLATE';
//Change configuration tab

export const CHANGE_SURVEY_QUESTION_SCREEN_BACKGROUND_COLOR =
  'CHANGE_SURVEY_QUESTION_SCREEN_BACKGROUND_COLOR';
export const CHANGE_SURVEY_TITLE_FONT_COLOR = 'CHANGE_SURVEY_TITLE_FONT_COLOR';
export const CHANGE_SURVEY_DESCRIPTION_FONT_COLOR = 'CHANGE_SURVEY_DESCRIPTION_FONT_COLOR';
export const CHANGE_SURVEY_BUTTON_FONT_COLOR = 'CHANGE_SURVEY_BUTTON_FONT_COLOR';
export const CHANGE_SURVEY_BUTTON_COLOR = 'CHANGE_SURVEY_BUTTON_COLOR';
export const RESET_SURVEY_CONFIGURATION_COLORS = 'RESET_SURVEY_CONFIGURATION_COLORS';

export const CREATE_SURVEY_THEMES_LOADING_STATUS = 'CREATE_SURVEY_THEMES_LOADING_STATUS';

export const GET_SURVEY_THEMES = 'GET_SURVEY_THEMES';
export const GET_SURVEY_THEMES_SUCCESS = 'GET_SURVEY_THEMES_SUCCESS';
export const GET_SURVEY_THEMES_ERROR = 'GET_SURVEY_THEMES_ERROR';

export const CHANGE_SURVEY_START_DATE = 'CHANGE_SURVEY_START_DATE';
export const CHANGE_SURVEY_END_DATE = 'CHANGE_SURVEY_END_DATE';
export const RESET_SURVEY_DATES = 'RESET_SURVEY_DATES';
export const GET_SURVEY_LIST_FOR_TABLE = 'GET_SURVEY_LIST_FOR_TABLE';
export const GET_SURVEY_LIST_FOR_TABLE_SUCCESS = 'GET_SURVEY_LIST_FOR_TABLE_SUCCESS';
export const GET_SURVEY_LIST_FOR_TABLE_FAIL = 'GET_SURVEY_LIST_FOR_TABLE_FAIL';

export const OPEN_ALERT = 'OPEN_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';

export const GET_SURVEY_QUESTIONS = 'GET_SURVEY_QUESTIONS';
export const GET_SURVEY_QUESTIONS_SUCCESS = 'GET_SURVEY_QUESTIONS_SUCCESS';
export const GET_SURVEY_QUESTIONS_ERROR = 'GET_SURVEY_QUESTIONS_ERROR';
export const UPDATE_SURVEY_FILTERS_PARAMETERS = 'UPDATE_SURVEY_FILTERS_PARAMETERS';
export const FILTERED_SURVEY_RESPONSE_LIST = 'FILTERED_SURVEY_RESPONSE_LIST';
export const SINGLE_FILTERED_SURVEY_RESPONSE = 'SINGLE_FILTERED_SURVEY_RESPONSE';
export const IS_SAVING = 'IS_SAVING';

export const CHANGE_SURVEY_BACKGROUND_IMAGE_URL = 'CHANGE_SURVEY_BACKGROUND_IMAGE_URL';
export const CHANGE_SURVEY_BACKGROUND_IMAGE_OPACITY = 'CHANGE_SURVEY_BACKGROUND_IMAGE_OPACITY';
export const CHANGE_SURVEY_BACKGROUND_IMAGE_FILE = 'CHANGE_SURVEY_BACKGROUND_IMAGE_FILE';
//survey Share Configuration
export const CHANGE_SPLASH_SCREEN_BACKGROUND_COLOR = 'CHANGE_SPLASH_SCREEN_BACKGROUND_COLOR';
export const CHANGE_SPLASH_SCREEN_DESCRIPTION_FONT_COLOR =
  'CHANGE_SPLASH_SCREEN_DESCRIPTION_FONT_COLOR';
export const CHANGE_SPLASH_SCREEN_BUTTON_FONT_COLOR = 'CHANGE_SPLASH_SCREEN_BUTTON_FONT_COLOR';
export const CHANGE_SPLASH_SCREEN_BUTTON_BACKGROUND_COLOR =
  'CHANGE_SPLASH_SCREEN_BUTTON_BACKGROUND_COLOR';
export const CHANGE_SPLASH_SCREEN_BUTTON_TEXT = 'CHANGE_SPLASH_SCREEN_BUTTON_TEXT';
export const CHANGE_SPLASH_SCREEN_DESCRIPTION_TEXT = 'CHANGE_SPLASH_SCREEN_DESCRIPTION_TEXT';
export const CHANGE_IFRAME_WIDTH = 'CHANGE_IFRAME_WIDTH';
export const CHANGE_IFRAME_LENGTH = 'CHANGE_IFRAME_LENGTH';
export const CHANGE_IS_SPLASH_SCREEN = 'CHANGE_IS_SPLASH_SCREEN';
export const RESET_SPLASH_SCREEN_CONFIGURATION = 'RESET_SPLASH_SCREEN_CONFIGURATION';
export const CLEAR_SURVEY_DATA = 'CLEAR_SURVEY_DATA';
export const UPDATE_PUBLISH_SURVEY = 'UPDATE_PUBLISH_SURVEY';
export const PUBLISH_SURVEY = 'PUBLISH_SURVEY';
export const SET_PIXEL_ID = 'SET_PIXEL_ID';

//post submission
export const CHANGE_POST_SURVEY_DESCRIPTION_TEXT = 'CHANGE_POST_SURVEY_DESCRIPTION_TEXT';
export const CHANGE_POST_SURVEY_IS_MLTIPLE_RESPONSE = 'CHANGE_POST_SURVEY_IS_MLTIPLE_RESPONSE';

export const SET_QUESTION_DEFINE_QUESTION_LIST = 'SET_QUESTION_DEFINE_QUESTION_LIST';
export const VIEW_SURVEY = 'VIEW_SURVEY';
export const UPDATE_SURVEY = 'UPDATE_SURVEY';
export const UPDATE_SURVEY_TITLE = 'UPDATE_SURVEY_TITLE';
export const UPDATE_SURVEY_DESCRIPTION = 'UPDATE_SURVEY_DESCRIPTION';

//update configuration

export const UPDATE_SURVEY_QUESTION_SCREEN_BACKGROUND_COLOR =
  'UPDATE_SURVEY_QUESTION_SCREEN_BACKGROUND_COLOR';
export const UPDATE_SURVEY_TITLE_FONT_COLOR = 'UPDATE_SURVEY_TITLE_FONT_COLOR';
export const UPDATE_SURVEY_DESCRIPTION_FONT_COLOR = 'UPDATE_SURVEY_DESCRIPTION_FONT_COLOR';
export const UPDATE_SURVEY_BUTTON_FONT_COLOR = 'UPDATE_SURVEY_BUTTON_FONT_COLOR';
export const UPDATE_SURVEY_BUTTON_COLOR = 'UPDATE_SURVEY_BUTTON_COLOR';
export const UPDATE_RESET_SURVEY_CONFIGURATION_COLORS = 'UPDATE_RESET_SURVEY_CONFIGURATION_COLORS';

export const UPDATE_SURVEY_START_DATE = 'UPDATE_SURVEY_START_DATE';
export const UPDATE_SURVEY_END_DATE = 'UPDATE_SURVEY_END_DATE';

export const UPDATE_SURVEY_BACKGROUND_IMAGE_URL = 'UPDATE_SURVEY_BACKGROUND_IMAGE_URL';
export const UPDATE_SURVEY_BACKGROUND_IMAGE_OPACITY = 'UPDATE_SURVEY_BACKGROUND_IMAGE_OPACITY';
export const UPDATE_SURVEY_BACKGROUND_IMAGE_FILE = 'UPDATE_SURVEY_BACKGROUND_IMAGE_FILE';
// update post submission

export const UPDATE_POST_SURVEY_DESCRIPTION_TEXT = 'UPDATE_POST_SURVEY_DESCRIPTION_TEXT';
export const UPDATE_POST_SURVEY_IS_MLTIPLE_RESPONSE = 'UPDATE_POST_SURVEY_IS_MLTIPLE_RESPONSE';
export const UPDATE_PIXEL_ID = 'UPDATE_PIXEL_ID';
//update splash screen

export const UPDATE_SPLASH_SCREEN_BACKGROUND_COLOR = 'UPDATE_SPLASH_SCREEN_BACKGROUND_COLOR';
export const UPDATE_SPLASH_SCREEN_DESCRIPTION_FONT_COLOR =
  'UPDATE_SPLASH_SCREEN_DESCRIPTION_FONT_COLOR';
export const UPDATE_SPLASH_SCREEN_BUTTON_FONT_COLOR = 'UPDATE_SPLASH_SCREEN_BUTTON_FONT_COLOR';
export const UPDATE_SPLASH_SCREEN_BUTTON_BACKGROUND_COLOR =
  'UPDATE_SPLASH_SCREEN_BUTTON_BACKGROUND_COLOR';
export const UPDATE_SPLASH_SCREEN_BUTTON_TEXT = 'UPDATE_SPLASH_SCREEN_BUTTON_TEXT';
export const UPDATE_SPLASH_SCREEN_DESCRIPTION_TEXT = 'UPDATE_SPLASH_SCREEN_DESCRIPTION_TEXT';
export const UPDATE_IFRAME_WIDTH = 'UPDATE_IFRAME_WIDTH';
export const UPDATE_IFRAME_LENGTH = 'UPDATE_IFRAME_LENGTH';
export const UPDATE_IS_SPLASH_SCREEN = 'UPDATE_IS_SPLASH_SCREEN';
export const UPDATE_RESET_SPLASH_SCREEN_CONFIGURATION = 'UPDATE_RESET_SPLASH_SCREEN_CONFIGURATION';

export const PREPARE_CHECKBOX_ANSWER_LIST = 'PREPARE_CHECKBOX_ANSWER_LIST';

export const HANDLE_SUBMIT_ERRORS = 'HANDLE_SUBMIT_ERRORS';
export const PREVIEW_SURVEY_FETCH_SURVEY = 'PREVIEW_SURVEY_FETCH_SURVEY';
export const SET_STEP_COUNT = 'SET_STEP_COUNT';
export const PREPARE_RESPONSE_LIST = 'PREPARE_RESPONSE_LIST';
export const PREPARE_TEXT_RESPONSE_MAP = 'PREPARE_TEXT_RESPONSE_MAP';
export const SET_STEP = 'SET_STEP';
export const SET_DIRECTION = 'SET_DIRECTION';
export const SET_VALUE = 'SET_VALUE';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const FILTER_QUESTIONS = 'FILTER_QUESTIONS';
export const RESET_PREVIEW_SURVEY = 'RESET_PREVIEW_SURVEY';
export const SET_IS_UPDATE_SHEET = 'SET_IS_UPDATE_SHEET';

//Update questions page action types
export const EDIT_UPDATE_QUESTION_PAGE_QUESTIONS = 'EDIT_UPDATE_QUESTION_PAGE_QUESTIONS';

// Survey Creation : handle validations
export const CHANGE_SURVEY_TITLE_VALIDATION = 'CHANGE_SURVEY_TITLE_VALIDATION';
export const CHANGE_VALIDATIONS = 'CHANGE_VALIDATIONS';

// Survey Updation : handle validations
export const UPDATE_SURVEY_TITLE_VALIDATION = 'UPDATE_SURVEY_TITLE_VALIDATION';
export const UPDATE_VALIDATIONS = 'UPDATE_VALIDATIONS';

// Survey template redux actions
export const FETCH_TEMPLATE_LIST = 'FETCH_TEMPLATE_LIST';
// Create from  template redux actions
export const CREATE_FROM_TEMPLATE = 'CREATE_FROM_TEMPLATE';
export const SET_QUESTION__LIST = 'SET_QUESTION__LIST';


//update conditional question data
export const ADD_CONDITIONAL_QUESTION = 'ADD_CONDITIONAL_QUESTION';
export const UPDATE_CONDITIONAL_QUESTION = 'UPDATE_CONDITIONAL_QUESTION';
export const GET_SURVEY_CONDITIONAL_QUESTIONS_SUCCESS = 'GET_SURVEY_CONDITIONAL_QUESTIONS_SUCCESS';

export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
